targets:
  $default:
    builders:
      graphql_to_dart:ast_generator:
        options:
          helper_path: graphql/common
          helper_filename: common_client_helpers.dart
          graphql_custom_type_base_filename: scalars/graphql_custom_type_base.dart
          models_import_path: /
          models_package: models
          package_name: massagex          
          graphql_endpoint: http://localhost:3000/graphql
          models_directory_path: lib/graphql/models/
          to_json_exclude_null_field: true
          use_equatable: true
          required_input_field: true
          type_override:
            Upload: MultipartFile
            # JSONObject: String
            # EmailAddress: String
            # PhoneNumber: String
          custom_scalar_implementation_paths:
            JSONObject: 'scalars/json_object.dart'
            EmailAddress: 'scalars/email_address.dart'
            PhoneNumber: 'scalars/phone_number.dart'